using System.Data;

namespace TData
{
    internal readonly struct DbCommandConfiguration
    {
        public readonly CommandBehavior CommandBehavior;
        public readonly MethodHandled MethodHandled;
        public readonly bool KeyAsReturnValue;
        public readonly bool SkipAutoGeneratedColumn;
        public readonly bool GenerateParameterWithKeys;

        internal DbCommandConfiguration(in CommandBehavior commandBehavior, in MethodHandled methodHandled, in bool skipAutoGeneratedColumn, in bool keyAsReturnValue, in bool generateParameterWithKeys)
        {
            SkipAutoGeneratedColumn = skipAutoGeneratedColumn;
            CommandBehavior = commandBehavior;
            MethodHandled = methodHandled;
            KeyAsReturnValue = keyAsReturnValue;
            GenerateParameterWithKeys = generateParameterWithKeys;
        }

        readonly internal bool IsTuple()
        {
            return MethodHandled == MethodHandled.FetchTupleQueryString_2 ||
                    MethodHandled == MethodHandled.FetchTupleQueryString_3 ||
                    MethodHandled == MethodHandled.FetchTupleQueryString_4 ||
                    MethodHandled == MethodHandled.FetchTupleQueryString_5 ||
                    MethodHandled == MethodHandled.FetchTupleQueryString_6 ||
                    MethodHandled == MethodHandled.FetchTupleQueryString_7;
        }

        readonly internal bool EligibleForAddOracleCursors() => MethodHandled == MethodHandled.FetchListQueryString || MethodHandled == MethodHandled.FetchOneQueryString || IsTuple();
        readonly internal bool IsExecuteNonQuery() => MethodHandled == MethodHandled.Execute;
        public override int GetHashCode()
        {
            var hash = 17;
            hash = (hash * 23) + CommandBehavior.GetHashCode();
            hash = (hash * 23) + MethodHandled.GetHashCode();
            hash = (hash * 23) + KeyAsReturnValue.GetHashCode();
            hash = (hash * 23) + GenerateParameterWithKeys.GetHashCode();
            return hash;
        }
    }
}
