using System.Reflection;

namespace Thomas.Database.Core.FluentApi
{
    public class DbColumn
    {
        public bool Autogenerated { get; set; }
        public bool Required { get; set; }
        public string Name { get; set; }
        private string _dbName;

        public string DbName
        {
            get
            {

                if (string.IsNullOrEmpty(_dbName))
                    return Name;

                return _dbName;
            }
            set { _dbName = value; }
        }

        public string FullDbName
        {
            get
            {
                if (string.IsNullOrEmpty(_dbName))
                    return Name;

                return $"{_dbName} AS {Name}";
            }
        }
        public int MaxLength { get; set; }
        public int MinLength { get; set; }
        public PropertyInfo Property { get; set; }
        public object DbType { get; set; }
    }
}
