using System.Reflection;

namespace TData.Core.FluentApi
{
    public class DbColumn
    {
        internal bool AutoGenerated { get; set; }
        internal string Name { get; set; }
        internal string DbName { get; set; }
        internal string FullDbName
        {
            get
            {
                if (string.IsNullOrEmpty(DbName))
                    return Name;

                return $"{DbName} AS {Name}";
            }
        }
        internal PropertyInfo Property { get; set; }

        //cast to specific type in database 
        internal string DbType { get; set; }

        internal int Size { get; set; }
        internal int Scale { get; set; }
        internal int Precision { get; set; }
        internal bool Configurated { get; set; }
        internal bool ForceCast { get; set; }
        internal bool LongTextTreatment { get; set; }

        //skip branching reader.IsDbNull(i) in the reader regardless of the column schema
        internal bool? IsNotNull { get; set; }
    }
}
