using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace TData.Core.FluentApi
{
    public class TableBuilder
    {
        internal Dictionary<string, DbTable> Tables;

        public TableBuilder()
        {
            Tables = new Dictionary<string, DbTable>();
        }

        public DbTable Configure<T>()
        {
            var tableType = typeof(T);
            var table = new DbTable { Name = tableType.Name! };
            Tables.Add(tableType.FullName!, table);
            return table;
        }

        public DbTable AddTable<T>(Expression<Func<T, object>> key, bool keyAutoGenerated = true)
        {
            var memberExpression = EnsureSelectedMember(key);
            var keyColumnName = memberExpression.Member.Name;
            var tableType = key.Parameters[0].Type;
            var keyColumn = new DbColumn { Name = keyColumnName, Property = tableType.GetProperty(keyColumnName)!, AutoGenerated = keyAutoGenerated, Configurated = true };
            var table = new DbTable
            {
                Name = tableType.Name!,
                Key = keyColumn
            };
            table.Columns = new LinkedList<DbColumn>(new[] { keyColumn });
            Tables.Add(tableType.FullName!, table);
            return table;
        }

        internal static void AddColumns(DbTable table, string key, Type type)
        {
            var properties = type.GetProperties();

            if (properties.Length == 0)
                throw new PropertiesNotFoundException($"No properties were found in the type '{type.FullName}'. Ensure that the type contains public properties.");

            foreach (var property in properties.Where(x => string.IsNullOrEmpty(key) || x.Name != key).ToArray())
            {
                table.Columns.AddLast(new DbColumn { Name = property.Name, Property = property, Configurated = true });
            }
        }

        internal static MemberExpression EnsureSelectedMember<T>(Expression<Func<T, object>> expression)
        {
            if (expression.Body is UnaryExpression unaryExpression && unaryExpression.Operand is MemberExpression memberExpression && expression.Parameters.Count == 1)
                return memberExpression;

            if (expression.Body is MemberExpression membExpression)
                return membExpression;

            throw new ArgumentException("Expression must be a member expression");

        }
    }
}
